name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Generate stats card (Dark - Dracula)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dracula&count_private=true
          path: profile/stats-dark.svg
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Generate stats card (Light - Catppuccin Latte)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=catppuccin_latte&count_private=true
          path: profile/stats-light.svg
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Generate top languages card (Dark - Dracula)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=donut&show_icons=true&theme=dracula&count_private=true
          path: profile/top-langs-dark.svg
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Generate top languages card (Light - Catppuccin Latte)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=donut&show_icons=true&theme=catppuccin_latte&count_private=true
          path: profile/top-langs-light.svg
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git pull --rebase
          git push
